# Harr component installation and version status.

readonly HARR_LEANCTX_VERSION="3.9.15"
readonly HARR_GITLAB_MCP_VERSION="2.1.48"
readonly HARR_CODEGRAPH_VERSION="1.5.0"
readonly HARR_SUPERGATEWAY_VERSION="3.4.3"

write_runtime_env() {
  local node_bin="$1"
  local node_bin_dir
  node_bin_dir="$(cd -- "$(dirname -- "$node_bin")" && pwd)"

  ensure_private_dir "$HARR_CONFIG_DIR"
  cat >"$HARR_RUNTIME_ENV" <<EOF_RUNTIME
# Managed by Harr. Regenerated by: harr install mcp
HARR_NODE_BIN_DIR=${node_bin_dir}
HARR_NPM_BIN_DIR=${HARR_NPM_BIN_DIR}
EOF_RUNTIME
  chmod 0600 "$HARR_RUNTIME_ENV"
}

check_node_runtime() {
  require_command node
  require_command npm

  local node_bin major
  node_bin="$(command -v node)"
  major="$(node -p 'Number(process.versions.node.split(".")[0])')"
  [[ "$major" =~ ^[0-9]+$ ]] || die 'could not determine Node.js major version'
  ((major >= 20 && major < 25)) || \
    die "Node.js 20-24 is required by the pinned CodeGraph build; current: $(node --version)"

  printf '%s\n' "$node_bin"
}

install_codegraph_wrapper() {
  local wrapper_src="${HARR_LIBEXEC_DIR}/mcp/codegraph-cli"
  local target="${HOME}/.local/bin/codegraph"
  local backup_dir="${HARR_LIBEXEC_DIR}/backup"

  [[ -x "$wrapper_src" ]] || die "CodeGraph wrapper missing: $wrapper_src"
  install -d -m 0755 "${HOME}/.local/bin" "$backup_dir"
  if [[ -e "$target" ]] && ! grep -q 'HARR_CODEGRAPH_WRAPPER=1' "$target" 2>/dev/null; then
    if [[ ! -e "${backup_dir}/codegraph.pre-harr" ]]; then
      cp -a "$target" "${backup_dir}/codegraph.pre-harr"
      printf 'Backed up previous codegraph launcher to %s\n' "${backup_dir}/codegraph.pre-harr"
    fi
  fi
  install -m 0755 "$wrapper_src" "$target"
}

patch_supergateway_loopback() {
  local node_bin="$1"
  local file="${HARR_NPM_PREFIX}/node_modules/supergateway/dist/gateways/stdioToStatefulStreamableHttp.js"
  [[ -f "$file" ]] || die "Supergateway bridge file not found: $file"

  "$node_bin" - "$file" <<'EOF_NODE'
const fs = require('fs');
const file = process.argv[2];
let text = fs.readFileSync(file, 'utf8');
const oldNeedle = 'app.listen(port, () => {';
const newNeedle = "app.listen(port, '127.0.0.1', () => {";
if (text.includes(newNeedle)) process.exit(0);
if (!text.includes(oldNeedle)) {
  console.error(`Harr refused to patch unknown Supergateway layout: ${file}`);
  process.exit(1);
}
text = text.replace(oldNeedle, newNeedle);
fs.writeFileSync(file, text);
EOF_NODE
}

install_node_mcp_stack() {
  local node_bin
  node_bin="$(check_node_runtime)"

  install -d -m 0755 "$HARR_NPM_PREFIX"
  cat >"${HARR_NPM_PREFIX}/package.json" <<EOF_PACKAGE
{
  "name": "harr-mcp-runtime",
  "private": true,
  "dependencies": {
    "@zereight/mcp-gitlab": "${HARR_GITLAB_MCP_VERSION}",
    "@colbymchenry/codegraph": "${HARR_CODEGRAPH_VERSION}",
    "supergateway": "${HARR_SUPERGATEWAY_VERSION}"
  }
}
EOF_PACKAGE

  printf 'Installing Harr MCP runtime packages...\n'
  PATH="$(dirname -- "$node_bin"):${PATH}" \
    npm install \
      --prefix "$HARR_NPM_PREFIX" \
      --omit=dev \
      --no-audit \
      --no-fund \
      --package-lock=false

  [[ -x "${HARR_NPM_BIN_DIR}/zereight-mcp-gitlab" ]] || \
    die 'GitLab MCP launcher was not installed'
  [[ -x "${HARR_NPM_BIN_DIR}/codegraph" ]] || \
    die 'CodeGraph launcher was not installed'
  [[ -x "${HARR_NPM_BIN_DIR}/supergateway" ]] || \
    die 'Supergateway launcher was not installed'

  patch_supergateway_loopback "$node_bin"
  write_runtime_env "$node_bin"
  install_codegraph_wrapper
}

leanctx_target() {
  local arch libc glibc_ver major minor
  arch="$(uname -m)"
  case "$arch" in
    x86_64) arch=x86_64 ;;
    arm64|aarch64) arch=aarch64 ;;
    *) die "unsupported LeanCTX architecture: $arch" ;;
  esac

  libc=musl
  if command -v ldd >/dev/null 2>&1; then
    glibc_ver="$(ldd --version 2>&1 | head -1 | grep -oE '[0-9]+\.[0-9]+$' || true)"
    if [[ -n "$glibc_ver" ]]; then
      major="${glibc_ver%%.*}"
      minor="${glibc_ver##*.}"
      if ((major > 2 || (major == 2 && minor >= 35))); then
        libc=gnu
      fi
    fi
  fi
  printf '%s\n' "${arch}-unknown-linux-${libc}"
}

verify_sha256() {
  local file="$1" expected="$2" actual
  if command -v sha256sum >/dev/null 2>&1; then
    actual="$(sha256sum "$file" | awk '{print $1}')"
  elif command -v shasum >/dev/null 2>&1; then
    actual="$(shasum -a 256 "$file" | awk '{print $1}')"
  else
    die 'sha256sum or shasum is required to install LeanCTX'
  fi
  [[ "$actual" == "$expected" ]] || die "LeanCTX checksum mismatch: expected $expected, got $actual"
}

install_leanctx_wrapper() {
  local wrapper_src="${HARR_LIBEXEC_DIR}/leanctx/lean-ctx-wrapper"
  local target="${HOME}/.local/bin/lean-ctx"
  local backup_dir="${HARR_LIBEXEC_DIR}/backup"

  [[ -x "$wrapper_src" ]] || die "LeanCTX wrapper missing: $wrapper_src"
  install -d -m 0755 "${HOME}/.local/bin" "$backup_dir"

  if [[ -e "$target" ]] && ! grep -q 'HARR_LEANCTX_WRAPPER=1' "$target" 2>/dev/null; then
    if [[ ! -e "${backup_dir}/lean-ctx.pre-harr" ]]; then
      cp -a "$target" "${backup_dir}/lean-ctx.pre-harr"
      printf 'Backed up previous lean-ctx launcher to %s\n' "${backup_dir}/lean-ctx.pre-harr"
    fi
  fi

  install -m 0755 "$wrapper_src" "$target"
}

install_leanctx() {
  require_command curl
  require_command tar

  local target version_dir real_bin tmpdir archive sums expected asset sums_url
  target="$(leanctx_target)"
  version_dir="${HARR_VENDOR_DIR}/lean-ctx/${HARR_LEANCTX_VERSION}"
  real_bin="${version_dir}/lean-ctx"

  if [[ -x "$real_bin" ]] && "$real_bin" --version 2>/dev/null | grep -q "${HARR_LEANCTX_VERSION}"; then
    printf 'LeanCTX %s already installed in Harr vendor dir.\n' "$HARR_LEANCTX_VERSION"
    install_leanctx_wrapper
    return
  fi

  tmpdir="$(mktemp -d)"
  archive="${tmpdir}/lean-ctx.tar.gz"
  sums="${tmpdir}/SHA256SUMS"
  asset="https://github.com/yvgude/lean-ctx/releases/download/v${HARR_LEANCTX_VERSION}/lean-ctx-${target}.tar.gz"
  sums_url="https://github.com/yvgude/lean-ctx/releases/download/v${HARR_LEANCTX_VERSION}/SHA256SUMS"

  printf 'Installing LeanCTX %s (%s)...\n' "$HARR_LEANCTX_VERSION" "$target"
  curl -fsSL "$asset" -o "$archive"
  curl -fsSL "$sums_url" -o "$sums"
  expected="$(awk -v f="lean-ctx-${target}.tar.gz" '$2 == f || $2 == "*" f {print $1; exit}' "$sums")"
  [[ -n "$expected" ]] || die "checksum entry not found for lean-ctx-${target}.tar.gz"
  verify_sha256 "$archive" "$expected"

  tar -xzf "$archive" -C "$tmpdir"
  [[ -x "${tmpdir}/lean-ctx" ]] || die 'LeanCTX archive did not contain lean-ctx executable'
  install -d -m 0755 "$version_dir"
  install -m 0755 "${tmpdir}/lean-ctx" "$real_bin"
  "$real_bin" --version | grep -q "${HARR_LEANCTX_VERSION}" || die 'installed LeanCTX version check failed'

  install_leanctx_wrapper
  rm -rf "$tmpdir"
}

cmd_install_components() {
  local target="${1:-all}"
  [[ $# -le 1 ]] || die 'usage: harr install [all|leanctx|mcp]'

  case "$target" in
    all)
      install_node_mcp_stack
      install_leanctx
      cmd_leanctx_apply
      ;;
    mcp|gitlab|codegraph)
      install_node_mcp_stack
      ;;
    leanctx)
      install_leanctx
      cmd_leanctx_apply
      ;;
    *) die 'usage: harr install [all|leanctx|mcp]' ;;
  esac
}

component_status_word() {
  local actual="$1" expected="$2"
  if [[ -z "$actual" ]]; then
    printf 'missing'
  elif [[ "$actual" == "$expected" ]]; then
    printf 'ok'
  else
    printf 'version-mismatch'
  fi
}

cmd_components_status() {
  local lean_actual='' gitlab_actual='' cg_actual='' sg_actual=''
  local lean_real="${HARR_VENDOR_DIR}/lean-ctx/${HARR_LEANCTX_VERSION}/lean-ctx"

  if [[ -x "$lean_real" ]]; then
    lean_actual="$("$lean_real" --version 2>/dev/null | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' | head -1 || true)"
  fi
  gitlab_actual="$(package_version "${HARR_NPM_PREFIX}/node_modules/@zereight/mcp-gitlab/package.json" 2>/dev/null || true)"
  cg_actual="$(package_version "${HARR_NPM_PREFIX}/node_modules/@colbymchenry/codegraph/package.json" 2>/dev/null || true)"
  sg_actual="$(package_version "${HARR_NPM_PREFIX}/node_modules/supergateway/package.json" 2>/dev/null || true)"

  printf '%-16s %-10s %-12s %s\n' COMPONENT EXPECTED STATE INSTALLED
  printf '%-16s %-10s %-12s %s\n' leanctx "$HARR_LEANCTX_VERSION" "$(component_status_word "$lean_actual" "$HARR_LEANCTX_VERSION")" "${lean_actual:--}"
  printf '%-16s %-10s %-12s %s\n' gitlab-mcp "$HARR_GITLAB_MCP_VERSION" "$(component_status_word "$gitlab_actual" "$HARR_GITLAB_MCP_VERSION")" "${gitlab_actual:--}"
  printf '%-16s %-10s %-12s %s\n' codegraph "$HARR_CODEGRAPH_VERSION" "$(component_status_word "$cg_actual" "$HARR_CODEGRAPH_VERSION")" "${cg_actual:--}"
  printf '%-16s %-10s %-12s %s\n' supergateway "$HARR_SUPERGATEWAY_VERSION" "$(component_status_word "$sg_actual" "$HARR_SUPERGATEWAY_VERSION")" "${sg_actual:--}"
}
